---
- hosts: webservers
  become: true
  become_user: root

  tasks:
    - name: install httpd
      apt: name=apache2 state=present
    - name: start apache2
      service: name=apache2 state=started
