---
- hosts: webservers
  become: true
  become_user: root
  vars:
   DOCKER_PACKAGES:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"
    - name: Install packages needed for Docker
      apt:
        name: "{{ DOCKER_PACKAGES }}"
        state: present
        force_apt_get: "yes"
