---
- hosts: webservers
  become: true
  become_user: root

  tasks:
    - name: install docker
      apt: name=docker state=present
    - name: start docker
      service: name=docker state=started enabled=yes
