---
- hosts: webservers
  become: true
  become_user: root
  
  tasks:
    - name: Start the Container
      docker_container:
        name: project
        image:  "kabejames/webapp:v3"
        state:  started
        published_ports:
          - 0.0.0.0:8181:8181
