---
- hosts: webservers
  become: true
  become_user: root
  
  tasks:
    - name: Install Docker
      apt:
        name: docker
        state:  present
    - name: start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Docker-py
      pip:
        name: docker-py
        state:  present
    - name: Start the Container
      docker_container:
        name: project
        image:  "kabejames/webapp:v13"
        state:  started
        restart: yes
        ports:
         - "8083:8083"
      
