---
- hosts: webservers
  become: true
  become_user: root
  
  tasks:
    - name: Install Docker-py
      pip:
        name: docker-py
        state:  present
    - name: Start the Container
      docker_container:
        name: project
        image:  "kabejames/webapp:v6"
        state:  started
        restart: yes
        ports:
         - "8080:9000"
      
